create table if not exists public.leaderboard (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 1 and 14),
    country text not null,
    score integer not null check (score > 0),
    created_at timestamptz not null default now()
);

alter table public.leaderboard enable row level security;

create policy "Anyone can read leaderboard"
on public.leaderboard
for select
using (true);

create policy "Anyone can submit scores"
on public.leaderboard
for insert
with check (score > 0 and char_length(name) between 1 and 14);
