create table if not exists public.leaderboard (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 1 and 14),
    country text not null,
    score integer not null check (score > 0),
    created_at timestamptz not null default now()
);

alter table public.leaderboard enable row level security;

drop policy if exists "Anyone can read leaderboard" on public.leaderboard;
drop policy if exists "Anyone can submit scores" on public.leaderboard;

-- Remove existing restrictive insert policy
DROP POLICY IF EXISTS "Allow public insert" ON leaderboard;

-- Create an open INSERT policy for anonymous submissions
CREATE POLICY "Allow public insert"
ON leaderboard
FOR INSERT
TO anon
WITH CHECK (
    score > 0 
    AND name IS NOT NULL 
    AND char_length(trim(name)) >= 1 
    AND char_length(trim(name)) <= 14
);
